version: "2"

linters:
  default: none
  enable:
    - errorlint
    - gochecksumtype
    - govet
    - modernize
    - staticcheck
    - testifylint
  exclusions:
    paths:
      - tmp/
      - .tmp/
