package gitwt

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

type zshCommandOptions struct {
	name  string
	out   string
	force bool
}

type generatedZshFile struct {
	kind  string
	path  string
	write func(string) error
}

func NewZshCommand() *cobra.Command {
	options := new(zshCommandOptions)

	command := &cobra.Command{
		Use:   `zsh`,
		Short: `Generate zsh wrapper, completion, and autoload helper for git-wt`,
		Args:  cobra.NoArgs,
		RunE:  options.Execute,
	}

	command.Flags().StringVarP(&options.name, `name`, `n`, `wt`, `name of generated zsh function`)
	command.Flags().StringVarP(&options.out, `out`, `o`, xdgDataHome()+`/zsh/site-functions`, `output directory for generated files`)
	command.Flags().BoolVarP(&options.force, `force`, `f`, false, `overwrite existing generated files`)

	return command
}

func (x *zshCommandOptions) Execute(command *cobra.Command, args []string) error {
	if err := os.MkdirAll(x.out, 0o755); err != nil {
		return fmt.Errorf(`create output directory: %w`, err)
	}

	generatedFiles := x.generatedFiles()
	if !x.force {
		if err := ensureGeneratedFilesDoNotExist(generatedFiles); err != nil {
			return err
		}
	}

	for _, generatedFile := range generatedFiles {
		if err := generatedFile.write(generatedFile.path); err != nil {
			return err
		}
	}

	return x.reportGeneratedFiles(command.ErrOrStderr(), generatedFiles)
}

func (x *zshCommandOptions) reportGeneratedFiles(output io.Writer, generatedFiles []generatedZshFile) error {
	for _, generatedFile := range generatedFiles {
		if _, err := fmt.Fprintf(output, "Wrote %s\n", generatedFile.path); err != nil {
			return fmt.Errorf("report generated file: %w", err)
		}
	}
	if _, err := fmt.Fprintf(output, "Ensure %s is on fpath. Restart zsh or run compinit if completion does not appear immediately.\n", x.out); err != nil {
		return fmt.Errorf("report fpath instructions: %w", err)
	}

	return nil
}

func (x *zshCommandOptions) generatedFiles() []generatedZshFile {
	return []generatedZshFile{
		{kind: "function", path: filepath.Join(x.out, x.name), write: x.writeFunctionFile},
		{kind: "completion", path: filepath.Join(x.out, `_`+x.name), write: x.writeCompletionFile},
		{kind: "autoload helper", path: filepath.Join(x.out, `_`+x.name+`_autoload`), write: x.writeAutoloadFile},
	}
}

func ensureGeneratedFilesDoNotExist(generatedFiles []generatedZshFile) error {
	for _, generatedFile := range generatedFiles {
		if _, err := os.Stat(generatedFile.path); err == nil {
			return fmt.Errorf(`%s file %q already exists; use --force to overwrite`, generatedFile.kind, generatedFile.path)
		}
	}

	return nil
}

func (x *zshCommandOptions) writeFunctionFile(target string) error {
	content := `# Generated by git-wt generate zsh
# DO NOT EDIT. Regenerate with git-wt generate zsh

` + x.name + `() {
    case "$1" in
    create)
        shift
        local no_cd=0 herdr=0 no_herdr=0 skip_next=0
        local -a forward=()
        local arg
        for arg in "$@"; do
            if (( skip_next )); then
                forward+=("$arg")
                skip_next=0
                continue
            fi
            case "$arg" in
            --no-cd)
                no_cd=1
                ;;
            --herdr)
                herdr=1
                forward+=("$arg")
                ;;
            --no-herdr)
                no_herdr=1
                forward+=("$arg")
                ;;
            -u|--upstream|-r|--repo)
                forward+=("$arg")
                skip_next=1
                ;;
            --upstream=*|--repo=*)
                forward+=("$arg")
                ;;
            -*)
                forward+=("$arg")
                ;;
            *)
                forward+=("$arg")
                ;;
            esac
        done
        # Write the created path to a temp file so git-wt keeps a real TTY for
        # interactive prompts (repo picker / name input). Capturing stdout would
        # blank the bubbletea UI.
        local path_file
        path_file=$(mktemp) || return $?
        GIT_WT_CREATE_PATH_FILE=$path_file command git-wt create "${forward[@]}"
        local create_status=$?
        local target_dir=""
        if [[ -s "$path_file" ]]; then
            target_dir=$(<"$path_file")
        fi
        rm -f "$path_file"
        if (( create_status != 0 )); then
            return $create_status
        fi
        if (( no_cd || herdr || ( ${HERDR_ENV:-0} == 1 && ! no_herdr ) )); then
            return 0
        fi
        if [[ -z "$target_dir" ]]; then
            echo "Created worktree path not reported" >&2
            return 1
        fi
        if ! [[ -d "$target_dir" ]]; then
            echo "Worktree not found at $target_dir" >&2
            return 1
        fi
        cd "$target_dir"
        ;;
    switch)
        shift
        local path_file
        path_file=$(mktemp) || return $?
        GIT_WT_SWITCH_PATH_FILE=$path_file command git-wt switch "$@"
        local switch_status=$?
        local target_dir=""
        if [[ -s "$path_file" ]]; then
            target_dir=$(<"$path_file")
        fi
        rm -f "$path_file"
        if (( switch_status != 0 )); then
            return $switch_status
        fi
        if [[ -z "$target_dir" ]]; then
            return 0
        fi
        if ! [[ -d "$target_dir" ]]; then
            echo "Worktree not found at $target_dir" >&2
            return 1
        fi
        cd "$target_dir"
        ;;
    repo)
        if [[ "$2" != rename ]]; then
            command git-wt "$@"
            return $?
        fi

        local path_file
        path_file=$(mktemp) || return $?
        GIT_WT_RENAME_PATH_FILE=$path_file command git-wt "$@"
        local rename_status=$?
        local target_dir=""
        if [[ -s "$path_file" ]]; then
            target_dir=$(<"$path_file")
        fi
        rm -f "$path_file"
        if (( rename_status != 0 )); then
            return $rename_status
        fi
        if [[ -n "$target_dir" ]]; then
            if ! [[ -d "$target_dir" ]]; then
                echo "Renamed worktree not found at $target_dir" >&2
                return 1
            fi
            cd "$target_dir" || return $?
        fi
        ;;
    remove|migrate)
        # Snapshot cwd, then leave it before the source path may disappear.
        # remove deletes the current worktree; migrate may delete a sole default
        # checkout or move the source tree out from under the shell.
        local previous_dir=$PWD
        cd "$HOME" || return $?
        (
            cd "$previous_dir" || exit $?
            command git-wt "$@"
        ) || return $?
        cd "$HOME"
        ;;
    *)
        command git-wt "$@"
        ;;
    esac
}
`

	return os.WriteFile(target, []byte(content), 0o644)
}

func (x *zshCommandOptions) writeAutoloadFile(target string) error {
	content := `#autoload ` + x.name + `

# Generated by git-wt generate zsh
# DO NOT EDIT. Regenerate with git-wt generate zsh
`

	return os.WriteFile(target, []byte(content), 0o644)
}

func (x *zshCommandOptions) writeCompletionFile(target string) error {
	content := `#compdef ` + x.name + `

# Generated by git-wt generate zsh
# DO NOT EDIT. Regenerate with git-wt generate zsh

_` + x.name + `() {
    local context state state_descr line
    typeset -A opt_args

    local -a subcommands
    subcommands=(
        'create:Create a managed Git worktree'
        'list:List managed Git worktrees'
        'migrate:Register a clone as bare, or rehome worktrees'
        'prune:Remove clean merged managed worktrees'
        'remove:Remove a managed Git worktree'
        'repo:Manage registered repositories'
        'setup-space:Set up a Herdr space for a managed Git worktree'
        'generate:Generate shell integration'
        'switch:Switch to a worktree'
    )

    if (( CURRENT == 2 )); then
        _describe 'command' subcommands
        return
    fi

    case $words[2] in
    create)
        shift words
        (( CURRENT-- ))
        _arguments -M 'r:|=*' \
            '--no-cd[Create without changing directories]' \
            '(-r --repo)'{-r,--repo}'[Registered repository name]:repository:->repos' \
            '(--no-herdr)--herdr[Also create a Herdr workspace for the new worktree]' \
            '(--herdr)--no-herdr[Do not create a Herdr workspace]' \
            '(-u --upstream)'{-u,--upstream}'[Upstream branch]:upstream branch:' \
            '(-h --help)'{-h,--help}'[help for create]' \
            '1:worktree name:_guard "[^-]*" "worktree name"'
        ;;
    list)
        shift words
        (( CURRENT-- ))
        _arguments \
            '(-a --all)'{-r,--repo}'[Registered repository name]:repository:->repos' \
            '(-r --repo)'{-a,--all}'[List worktrees from all registered repositories]' \
            '(-h --help)'{-h,--help}'[help for list]'
        ;;
    switch)
        shift words
        (( CURRENT-- ))
        local completing_switch=1
        _arguments -M 'r:|=*' \
            '(-a --all)'{-c,--create}'[Create the worktree if it does not exist]' \
            '--no-cd[Create without changing directories]' \
            '(-r --repo)'{-r,--repo}'[Registered repository name]:repository:->repos' \
            '(-c --create)'{-a,--all}'[Ignore the current worktree repository]' \
            '(--no-herdr)--herdr[Also create a Herdr workspace for the new worktree]' \
            '(--herdr)--no-herdr[Do not create a Herdr workspace]' \
            '(-u --upstream)'{-u,--upstream}'[Upstream branch]:upstream branch:' \
            '1:worktree name:->switch_name'
        ;;
    remove)
        shift words
        (( CURRENT-- ))
        _arguments \
            '(-r --repo)'{-r,--repo}'[Registered repository name]:repository:->repos' \
            '1:worktree name:->worktrees'
        ;;
    setup-space)
        shift words
        (( CURRENT-- ))
        _arguments \
            '(-r --repo)'{-r,--repo}'[Registered repository name]:repository:->repos' \
            '(-n --new)'{-n,--new}'[Open a new Herdr workspace]' \
            '1:worktree name:->worktrees'
        ;;
    prune)
        shift words
        (( CURRENT-- ))
        _arguments \
            '(-r --repo)'{-r,--repo}'[Registered repository name]:repository:->repos' \
            '(-p --prompt)'{-p,--prompt}'[Prompt before pruning]' \
            '(-n --dry-run)'{-n,--dry-run}'[List worktrees that would be pruned]' \
            '(-h --help)'{-h,--help}'[help for prune]'
        ;;
    migrate)
        shift words
        (( CURRENT-- ))
        _arguments \
            '--name[Repository name]:repository name:' \
            '(-p --prompt)'{-p,--prompt}'[Prompt before migrating worktrees]' \
            '(-a --all)'{-a,--all}'[Rehome worktrees for every registered repository]' \
            '(-h --help)'{-h,--help}'[help for migrate]'
        ;;
    repo)
        local -a repo_commands
        repo_commands=(
            'add:Register a bare repository'
            'list:List registered repositories'
            'remove:Remove a registered repository'
            'rename:Rename a registered repository'
        )
        if (( CURRENT == 3 )); then
            _describe 'repo command' repo_commands
            return
        fi
        case $words[3] in
        list)
            shift words
            (( CURRENT-- ))
            shift words
            (( CURRENT-- ))
            _arguments \
                '(-q --quiet)'{-q,--quiet}'[Print repository names only]' \
                '(-h --help)'{-h,--help}'[help for list]'
            ;;
        remove)
            state=repos
            ;;
        rename)
            if (( CURRENT == 4 )); then
                state=repos
            elif (( CURRENT == 5 )); then
                _message 'new repository name'
                return
            fi
            ;;
        esac
        ;;
    esac

    case $state in
    switch_name)
        if (( ${words[(I)-c]} || ${words[(I)--create]} )); then
            _message 'worktree name'
            return
        fi
        ;;
    esac
    if [[ $state == switch_name ]]; then
        state=worktrees
    fi

    case $state in
    repos)
        local -a repos
        local data_home=${XDG_DATA_HOME:-$HOME/.local/share}
        local worktree_root=${GIT_WT_WORKTREE_ROOT:-$HOME/worktrees}
        local filter_name=""
        local repo_dir repo_name i skip_next=0
        if (( completing_switch )) && (( ! ${words[(I)-c]} && ! ${words[(I)--create]} && ! ${words[(I)-a]} && ! ${words[(I)--all]} )); then
            for (( i = 1; i <= $#words; i++ )); do
                if (( skip_next )); then
                    skip_next=0
                    continue
                fi
                case ${words[i]} in
                --repo|-r|--upstream|-u)
                    skip_next=1
                    ;;
                -*)
                    ;;
                *)
                    filter_name=${words[i]}
                    break
                    ;;
                esac
            done
        fi
        for repo_dir in "$data_home"/git-wt/repos/*.git(N/); do
            repo_name=${repo_dir:t:r}
            if [[ -n "$filter_name" ]] && ! [[ -d "$worktree_root/$repo_name/$filter_name/$repo_name" ]]; then
                continue
            fi
            repos+=("$repo_name")
        done
        _describe 'repositories' repos
        ;;
    worktrees)
        local repo_name=""
        local i
        for (( i = 1; i <= $#words; i++ )); do
            case ${words[i]} in
            --repo|-r)
                repo_name=${words[i+1]}
                ;;
            --repo=*)
                repo_name=${words[i]#--repo=}
                ;;
            esac
        done
        local worktree_root=${GIT_WT_WORKTREE_ROOT:-$HOME/worktrees}
        if [[ -z "$repo_name" ]] && (( completing_switch )) && (( ! ${words[(I)-a]} && ! ${words[(I)--all]} )); then
            local data_home_for_cwd=${XDG_DATA_HOME:-$HOME/.local/share}
            local part=$PWD
            while [[ "$part" != "$worktree_root" && "$part" != "/" && "$part" != "." ]]; do
                local base=${part:t}
                if [[ "$part" == "$worktree_root"/* && -d "$data_home_for_cwd/git-wt/repos/${base}.git" ]]; then
                    repo_name=$base
                    break
                fi
                part=${part:h}
            done
        elif [[ -z "$repo_name" ]] && (( ! completing_switch )); then
            local common
            common=$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null) || return 0
            repo_name=${common:t}
            repo_name=${repo_name%.git}
        fi
        if [[ -z "$repo_name" ]] && (( completing_switch )); then
            local data_home=${XDG_DATA_HOME:-$HOME/.local/share}
            local -A name_count
            local repo_dir repo_name_i worktree_dir parent name
            for repo_dir in "$data_home"/git-wt/repos/*.git(N/); do
                repo_name_i=${repo_dir:t:r}
                for worktree_dir in "$worktree_root/$repo_name_i"/**/"$repo_name_i"(N/); do
                    parent=${worktree_dir:h}
                    name=${parent#$worktree_root/$repo_name_i/}
                    if [[ -n "$name" && "$name" != "$parent" ]]; then
                        name_count[$name]=$(( ${name_count[$name]:-0} + 1 ))
                    fi
                done
            done
            local -a unique_names ambiguous_names
            for name in ${(k)name_count}; do
                if [[ ${name_count[$name]} -eq 1 ]]; then
                    unique_names+=("$name")
                else
                    ambiguous_names+=("$name")
                fi
            done
            local ret=1
            (( $#unique_names )) && compadd -S '' -- "${unique_names[@]}" && ret=0
            (( $#ambiguous_names )) && compadd -S ' --repo ' -- "${ambiguous_names[@]}" && ret=0
            return $ret
        fi
        if [[ -z "$repo_name" ]]; then
            return 0
        fi
        local -a worktrees
        local worktree_dir parent name
        for worktree_dir in "$worktree_root/$repo_name"/**/"$repo_name"(N/); do
            parent=${worktree_dir:h}
            name=${parent#$worktree_root/$repo_name/}
            if [[ -n "$name" && "$name" != "$parent" ]]; then
                worktrees+=("$name")
            fi
        done
        _describe 'worktrees' worktrees
        ;;
    esac
}
`

	return os.WriteFile(target, []byte(content), 0o644)
}
