package gitwt

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

type zshCommandOptions struct {
	name  string
	out   string
	force bool
}

func NewZshCommand() *cobra.Command {
	options := &zshCommandOptions{}

	command := &cobra.Command{
		Use:   `zsh`,
		Short: `Generate zsh function and completion wrapping git-wt`,
		Args:  cobra.NoArgs,
		RunE:  options.Execute,
	}

	command.Flags().StringVarP(&options.name, `name`, `n`, `wt`, `name of generated zsh function`)
	command.Flags().StringVarP(&options.out, `out`, `o`, xdgDataHome()+`/zsh/site-functions`, `output directory for generated files`)
	command.Flags().BoolVarP(&options.force, `force`, `f`, false, `overwrite existing generated files`)

	return command
}

func xdgDataHome() string {
	if xdg := os.Getenv(`XDG_DATA_HOME`); xdg != `` {
		return xdg
	}
	return filepath.Join(os.Getenv(`HOME`), `.local`, `share`)
}

func (x *zshCommandOptions) Execute(command *cobra.Command, args []string) error {
	outDir := x.out

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf(`create output directory: %w`, err)
	}

	functionPath := filepath.Join(outDir, x.name)
	completionPath := filepath.Join(outDir, `_`+x.name)

	if !x.force {
		if _, err := os.Stat(functionPath); err == nil {
			return fmt.Errorf(`function file %q already exists; use --force to overwrite`, functionPath)
		}
		if _, err := os.Stat(completionPath); err == nil {
			return fmt.Errorf(`completion file %q already exists; use --force to overwrite`, completionPath)
		}
	}

	if err := x.writeFunctionFile(functionPath); err != nil {
		return err
	}

	if err := x.writeCompletionFile(completionPath); err != nil {
		return err
	}

	fmt.Fprintf(command.ErrOrStderr(), "Wrote %s\n", functionPath)
	fmt.Fprintf(command.ErrOrStderr(), "Wrote %s\n", completionPath)
	fmt.Fprintf(command.ErrOrStderr(), "Ensure %s is on fpath. Restart zsh or run compinit if completion does not appear immediately.\n", outDir)

	return nil
}

func (x *zshCommandOptions) writeFunctionFile(target string) error {
	content := `# Generated by git-wt generate zsh
# DO NOT EDIT. Regenerate with git-wt generate zsh

` + x.name + `() {
    case "$1" in
    create)
        shift
        local no_cd=0 herdr=0 no_herdr=0 name="" skip_next=0
        local -a forward=()
        local arg
        for arg in "$@"; do
            if (( skip_next )); then
                forward+=("$arg")
                skip_next=0
                continue
            fi
            case "$arg" in
            --no-cd)
                no_cd=1
                ;;
            -r|--herdr)
                herdr=1
                forward+=("$arg")
                ;;
            -R|--no-herdr)
                no_herdr=1
                forward+=("$arg")
                ;;
            -u|--upstream)
                forward+=("$arg")
                skip_next=1
                ;;
            --upstream=*)
                forward+=("$arg")
                ;;
            -*)
                forward+=("$arg")
                ;;
            *)
                forward+=("$arg")
                name=$arg
                ;;
            esac
        done
        command git-wt create "${forward[@]}" || return $?
        if (( no_cd || herdr || ( ${HERDR_ENV:-0} == 1 && ! no_herdr ) )); then
            return 0
        fi
        if [[ -z "$name" ]]; then
            echo "Usage: ` + x.name + ` create [--no-cd] [options] <name>" >&2
            return 1
        fi
        local main_dir
        main_dir=$(git worktree list --porcelain | head -n1 | sed "s/^worktree //")
        if [[ -z "$main_dir" ]]; then
            echo "Main worktree not found" >&2
            return 1
        fi
        local root_dir=${main_dir:h:h}
        local repo_name=${main_dir:t}
        local target_dir=$root_dir/$name/$repo_name
        if ! [[ -d "$target_dir" ]]; then
            echo "Worktree $name not found at $target_dir" >&2
            return 1
        fi
        cd "$target_dir"
        ;;
    switch)
        shift
        if [[ -z "$1" ]]; then
            echo "Usage: ` + x.name + ` switch <worktree>" >&2
            return 1
        fi

        local main_dir
        main_dir=$(git worktree list --porcelain | head -n1 | sed "s/^worktree //")
        if [[ -z "$main_dir" ]]; then
            echo "Main worktree not found" >&2
            return 1
        fi

        local arg=$1

        case "$arg" in
        main)
            if [[ $(pwd) == "$main_dir" ]]; then
                echo "Already in main worktree"
                return 0
            fi
            if ! [[ -d "$main_dir" ]]; then
                echo "Main worktree not found" >&2
                return 1
            fi
            cd "$main_dir"
            ;;
        *)
            local root_dir=${main_dir:h:h}
            local repo_name=${main_dir:t}
            local target_dir=$root_dir/$arg/$repo_name
            if [[ $(pwd) == "$target_dir" ]]; then
                echo "Already in $arg"
                return 0
            fi
            if ! [[ -d "$target_dir" ]]; then
                echo "Worktree $arg not found at $target_dir" >&2
                return 1
            fi
            cd "$target_dir"
            ;;
        esac
        ;;
    remove)
        local main_dir
        main_dir=$(git worktree list --porcelain | head -n1 | sed "s/^worktree //")
        if [[ -z "$main_dir" ]]; then
            echo "Main worktree not found" >&2
            return 1
        fi
        command git-wt "$@" || return $?
        cd "$main_dir"
        ;;
    off)
        local main_dir
        main_dir=$(git worktree list --porcelain | head -n1 | sed "s/^worktree //")
        if [[ -z "$main_dir" ]]; then
            echo "Main worktree not found" >&2
            return 1
        fi
        local root_dir=${main_dir:h:h}
        command git-wt "$@" || return $?
        cd "$root_dir"
        ;;
    *)
        command git-wt "$@"
        ;;
    esac
}
`

	return os.WriteFile(target, []byte(content), 0o644)
}

func (x *zshCommandOptions) writeCompletionFile(target string) error {
	content := `#compdef ` + x.name + `

# Generated by git-wt generate zsh
# DO NOT EDIT. Regenerate with git-wt generate zsh

_` + x.name + `() {
    local -a subcommands
    subcommands=(
        'create:Create a managed Git worktree'
        'list:List managed Git worktrees'
        'migrate:Bring existing worktrees under management'
        'off:Tear down managed worktrees into a single checkout'
        'prune:Remove clean merged managed worktrees'
        'remove:Remove a managed Git worktree'
        'generate:Generate shell integration'
        'switch:Switch to a worktree'
    )

    if (( CURRENT == 2 )); then
        _describe 'command' subcommands
        return
    fi

    case $words[2] in
    create)
        shift words
        (( CURRENT-- ))
        _arguments \
            '--no-cd[Create without changing directories]' \
            '(-r --herdr)'{-r,--herdr}'[Also create a Herdr workspace for the new worktree]' \
            '(-R --no-herdr)'{-R,--no-herdr}'[Do not create a Herdr workspace]' \
            '(-u --upstream)'{-u,--upstream}'[Upstream branch]:upstream branch:' \
            '(-h --help)'{-h,--help}'[help for create]' \
            '1:worktree name:'
        ;;
    switch|remove)
        if ! git rev-parse --is-inside-work-tree 1>/dev/null 2>/dev/null; then
            return 1
        fi

        local main_dir
        main_dir=$(git worktree list --porcelain | head -n1 | sed "s/^worktree //")
        local root_dir=${main_dir:h:h}
        local repo_name=${main_dir:t}

        local -a worktrees
        if [[ $words[2] == switch ]]; then
            worktrees=(main)
        fi

        local worktree_path="" line branch
        while IFS= read -r line; do
            case "$line" in
            'worktree '*)
                worktree_path=${line#worktree }
                ;;
            'branch refs/heads/'*)
                branch=${line#branch refs/heads/}
                if [[ "$worktree_path" != "$main_dir" && "$worktree_path" == "$root_dir/$branch/$repo_name" ]]; then
                    worktrees+=("$branch")
                fi
                ;;
            esac
        done < <(git worktree list --porcelain 2>/dev/null)

        _describe 'worktrees' worktrees
        ;;
    esac
}
`

	return os.WriteFile(target, []byte(content), 0o644)
}
